[[implfunkt]]
[appendix]
== Implizite Funktionalitäten

[[implfunkt_vorbemerkungen]]
=== Vorbemerkungen

Erläuterungen zu den Tabellen:

* Referent = Das Objekt, welches zeigt.
* Referenz = Die Verbindung (Relation) zwischen den Objekten, d.h. das,
womit gezeigt wird. In Sp. 2 der Tabellen wird stets nur die bevorzugte
Relationsrichtung genannt.
* Referenziertes = Das Objekt, worauf gezeigt wird.
* "Objekt Löschen" bedeutet, dass die aktuelle Version des untergehenden
Objektes ein Untergangsdatum erhält. Die bei Führung der "Rumpfhistorie"
zu einem späteren Zeitpunkt notwendige Entfernung des untergegangen
Objektes aus dem Bestand wird durch die impliziten Funktionen
vorbereitet.
* "Referenz Löschen" bedeutet in Abhängigkeit von der Art der Referenz,
dass
** eine neue Version des Objektes ohne die genannte ("bevorzugte") Referenz
gebildet wird ("Versionierung" des Objektes). Die bei Führung der
"Rumpfhistorie" zu einem späteren Zeitpunkt notwendige Entfernung der
historischen Version des Objektes aus dem Bestand wird damit
vorbereitet. o d e r
** die Referenz aus der aktuellen Version des Objektes entfernt wird (bei
Löschen der implementierungsspezifischen "Gegenreferenz" keine
"Versionierung" des Objektes).

Hinweis: Die teilweise in vorhandenen Systemen bestehende
Mehrfachbedeutung von Punkten (z.B.: Ein Punkt ist gleichzeitig
Aufnahmepunkt und Grenzpunkt) wird in den neuen Datenstrukturen
entzerrt: Solche Punkte werden zu verschiedenen Fachobjekten. Dadurch
verlagert sich mit der Mehrfachbedeutung verbundene Problematik im
Zusammenhang mit impliziter Funktionalität zum Teil auf die
Geometrieebene. Ausnahme: AU_*-Modellteile. Hier gilt: Abgeleitete
Objekte dürfen sich keine Geometrie mit anderen Objekten teilen.
Mehrfachbedeutung wird dadurch ausgeschlossen.

Implizite Funktionalität soll in einer Art Kettenreaktion wiederum
implizite Funktionalität bewirken können. Beispiel:

[Example]
====
AX_Buchungsstelle _wirdVerwaltetVon_ AX_Verwaltung _haengtAn_ AX_Person.
Wird AX_Person gelöscht und ist in der Folge auch AX_Verwaltung implizit
zu löschen, so ist als weitere Folge auch die Relation
_wirdVerwaltetVon_ implizit zu löschen.

====

Es werden nur Implizite Funktionen aufgeführt, die als Folge der
Löschung (in Ausnahmefällen auch der Eintragung) von Objekten notwendig
sind. Auch die Löschung und Veränderung von Relationen und Attributen
können Folgemaßnahmen zur Aufrechterhaltung der Konsistenz der Datenbank
erfordern; diese Maßnahmen sind jedoch entweder interaktiv oder implizit
am Erhebungs- bzw. Qualifizierungsarbeitsplatz zu generieren. Vom System
für die Datenhaltung ist zu fordern, dass Änderungen, deren Ergebnis den
Festlegungen der 3A- Kataloge zuwiderläuft, abgelehnt werden oder
zumindest eine entsprechende Meldung erzeugen.

Generell obliegt es den Systemen zum Primär- bzw. Sekundärnachweis dafür
zu sorgen, dass die den Fachobjekten zugrunde liegenden geometrischen
und topologischen Strukturen konsistent im Sinne von ISO 19107 sind und
bleiben. In den Tabellen wird daher auf Details diesbezüglich nicht
konkret eingegangen.

[[implfunkt_primaernachweis]]
=== Implizite Funktionen im Führungsprozess für ein System zum Primärnachweis

In der Zusammenstellung der Impliziten Funktionen im Führungsprozess für
ein System zum Primärnachweis wird unterschieden zwischen allgemein
gültigen Funktionen, die für alle Objektarten des 3A- Anwendungsschemas
gleichermaßen notwendig sind (Teil B1), und den besonderen Funktionen,
die für einzelne Objektarten (und ggf. Relationen) gefordert werden
(Teil B2). Der Hinweis im Teil B2 "Keine besondere implizite Funktion"
bedeutet, dass die im Teil B1 festgelegten "Allgemeinen Impliziten
Funktionen" anzuwenden sind.


==== Allgemein gültige Festlegungen für das AAA- Anwendungsschema

////

Tabellen größer als die Content-Area zu machen ist mit Bordmitteln nicht möglich. 
Bei Bedarf hilft ggfs. folgendes: https://stackoverflow.com/questions/58639752/asciidoctor-overflow-on-a-large-table

////

[width="100%",cols="8%,16%,14%,16%,46%",options="noheader",]
|===
2+|*Zu löschendes Objekt* |Betroffene Relation .2+|*"Implizit" betroffene
Objektart* |*Aktion der Datenhaltungskomponente*

2+|Objekt in Sp.1 wird gelöscht, wenn nichts anderes gesagt wird. |*Art des Mangels* |(D.h. was mit den Objekten in Spalte 3 bzw. der
Referenz geschehen soll)
 
|Nr. |Spalte 1 |Spalte 2 |Spalte 3 |Spalte 4

a|a)
a|Objekt A

NREO, REO, ZUSO

_REFERENT_
|... 
a|Objekt B

NREO, REO, ZUSO

_REFERENZIERTES_
|Wird Objekt A gelöscht, so werden mit ihm auch seine Referenzen,
Überführungs- und Unterführungsrelationen gelöscht.

a|b)
a|
Objekt A wird eingetragen

NREO, REO, ZUSO

_REFERENT_
a|...

*Gegenreferenz fehlt*

a|
Objekt B

NREO, REO, ZUSO

_REFERENZIERTES_
a|
* Die noch fehlende Gegenreferenz von Objekt B auf Objekt A ist
automatisch zu bilden und einzutragen
* Keine Versionierung von Objekt B.

a|c)
a|
Objekt A

NREO, REO, ZUSO

_REFERENT_
a|...

*Referenz fehlt*

a|Objekt B

NREO, REO, ZUSO

_REFERENZIERTES_
a|
* Die implementierungstechnische Gegenreferenz von Objekt B auf Objekt A
ist zu löschen
* Keine Versionierung von Objekt B
* Evtl. zusätzliche Maßnahmen oder Ausnahmen von diesen Regeln sind in
dem jeweiligen Subschema festgelegt.

a|d)
a|Objekt A

NREO, REO, ZUSO

_REFERENZIERTES_
a|...

*Referenz sinnlos*

a|Objekt B

NREO, REO, ZUSO

_REFERENT_
a|
* Die sinnlose Referenz von Objekt B auf Objekt A ist zu löschen
* Versionierung von Objekt B

* In Abhängigkeit von Konsistenzbedingungen muss ggf. für Ersatz bei dem
Nachfolger von A gesorgt werden.
* Evtl. zusätzliche Maßnahmen oder Ausnahmen von diesen Regeln sind in
dem jeweiligen Subschema festgelegt.

a|e)
a|Objekt A

NREO, REO, ZUSO

_REFERENT_
a|istTeilVon

*Referenz fehlt*
a|Objekt B

ZUSO

_REFERENZIERTES_
a|
* Prüfung, ob das Objekt A der letzte (einzige) Bestandteil des Objektes
B ist

** falls ja ist auch das Objekt B zu löschen
** gelöschte Objektart mit OID im Protokoll ausgeben

* Ausnahmen von diesen Regeln sind in dem jeweiligen Subschema
festgelegt.

a|f)
a|Objekt A

REO, ZUSO

_REFERENZIERTES_
a|dientZurDarstellungVon +
oder istAbgeleitetAus

*Referenz sinnlos*
a|Objekt der Objektartengruppe "Präsentation" oder "Kartengeometrie"

REO

_REFERENT_
a|Prüfung, ob das Objekt in Spalte 3 noch andere Objekte referenziert

* Falls ja: Warnhinweis ausgeben
* Falls nein: das betroffene Objekt B der Objektartengruppe "Präsentation"
bzw. "Kartengeometrie" löschen und gelöschte Objektart mit OID im
Protokoll ausgeben

|===


==== Festlegungen für einzelne Relationen des AFIS-Subschemas

[width="100%",cols="8%,16%,14%,16%,46%",options="noheader",]
|===
2+|*Zu löschendes Objekt* |Betroffene Relation .2+|*"Implizit" betroffene
Objektart* |*Aktion der Datenhaltungskomponente*

2+|Objekt in Sp.1 wird gelöscht, wenn nichts anderes gesagt wird. |*Art des Mangels* |(D.h. was mit den Objekten in Spalte 3 bzw. der
Referenz geschehen soll)
 
|Nr. |Spalte 1 |Spalte 2 |Spalte 3 |Spalte 4
a|
a|Objekt wird eingetragen:

AX_Lagefestpunkt,

AX_Höhenfestpunkt,

AX_Schwerefestpunkt,

AX_Referenzstations-

punkt

ZUSO

a|(Keine Relation!)

Name der Objektart in Sp. 1 semantisch identisch mit der
Werteart des Attributes 'Art' des Objektes AX_Reservierung
sowie Identität der Attributinhalte 'Punktkennung'

a|AX_Reservierung

NREO
a|
* Das betroffene Objekt AX_Reservierung ist zu löschen
* Ein entsprechender Protokolleintrag ist zu erzeugen.

|===

 
==== Festlegungen für einzelne Relationen des ALKIS- Subschemas

[width="100%",cols="8%,16%,14%,16%,46%",options="noheader",]
|===
2+|*Zu löschendes Objekt* |Betroffene Relation .2+|*"Implizit" betroffene
Objektart* |*Aktion der Datenhaltungskomponente*

2+|Objekt in Sp.1 wird gelöscht, wenn nichts anderes gesagt wird. |*Art des Mangels* |(D.h. was mit den Objekten in Spalte 3 bzw. der
Referenz geschehen soll)
 
|Nr. |Spalte 1 |Spalte 2 |Spalte 3 |Spalte 4

|00000 
a|*Objekt wird eingetragen:*

AX_Flurstueck, +
AX_Buchungsblatt, +
AX_FortfuehrungsNachweisDeckblatt, +
AX_Grenzpunkt,  +
AX_BesondererGebaeudepunkt, +
AX_Aufnahmepunkt, +
AX_Sicherungspunkt, +
AX_SonstigerVermessungspunkt, +
AX_BesondererBauwerkspunkt/ +
AX_BesondererTopographischerPunkt +
ZUSO
|(Keine Relation!) Name der Objektart in Sp. 1 semantisch identisch mit
der Werteart des Attributes 'Art' des Objektes AX_Reservierung sowie
Identität der Attributinhalte 'Punktkennung' bzw.
'Flurstuecks­kennzeichen' bzw. 'Fortführungs­nummer' bzw.
'Abmarkungs­protokollnummer' mit 'Nummer' a|
AX_Reservierung +
NREO
a|
* Das betroffene Objekt AX_Reservierung ist zu löschen
* Ein entsprechender Protokolleintrag ist zu erzeugen.

|11001 
a|AX_Flurstueck +
[.underline]#REO# +
*REFERENT*
a|istGebucht +
*Referenz fehlt*
a|AX_Buchungsstelle +
[.underline]#NREO# +
*REFERENZIERTES*
a|Prüfen, ob AX_Buchungsstelle noch anderweitig referenziert wird Falls
nein: AX_Buchungsstelle löschen und
gelöschte Objektart mit OID im Protokoll ausgeben

|11001 
a|AX_Flurstueck +
REO +
*REFERENZIERTES*
a|gehoertAnteiligZu +
*Referenz fehlt*
a|AX_Flurstueck +
REO +
*REFERENT* +
(z.B. Anliegerweg)
a|Hier wird ein Ersatzobjekt benötigt, daher:

* Warnhinweis im Protokoll ausgeben.

a|11001 +
12006 +
31001 +
51001
a|AX_Flurstueck +
AX_GeoreferenzierteGebaeudeadresse +
AX_Gebaeude +
AX_Turm +
REO +
*REFERENT*
a|weistAuf +
hatAuch +
zeigtAuf +
*Referenz fehlt*
a|AX_LagebezeichnungMitHausnummer +
NREO +
*REFERENZIERTES*
a|Prüfen, ob AX_LagebezeichnungMitHausnummer noch anderweitig referenziert
wird

* Falls nein: AX_LagebezeichnungMitHausnummer löschen und gelöschte
Objektart mit OID im Protokoll ausgeben.

|11001 
a|AX_Flurstueck +
REO +
*REFERENT*
a|zeigtAuf +
*Referenz fehlt*
a|AX_LagebezeichnungOhneHausnummer +
NREO +
*REFERENZIERTES*
a|Prüfen, ob AX_LagebezeichnungOhneHausnummer noch anderweitig
referenziert wird

* Falls nein: AX_LagebezeichnungOhneHausnummer löschen und gelöschte
Objektart mit OID im Protokoll ausgeben.

|11001 
a|AX_Flurstueck +
REO +
*REFERENZIERTES*
a|beziehtSichAuf +
*Referenz sinnlos*
a|AX_Vertretung +
NREO

_REFERENT_
a|Prüfen, ob AX_Vertretung noch andere Flurstücke referenziert.

* Falls nein: AX_Vertretung löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|11003 
a|AX_Grenzpunkt +
ZUSO +
*REFERENZIERTES*
a|zeigtAuf +
*Referenz sinnlos*
a|AX_Grenzpunkt +
ZUSO

_REFERENT_ +
Indirekt abgemarkter Grenzpunkt außerhalb der Flurstücksgrenze.
|Warnhinweis im Protokoll ausgeben.

a|11003 +
13001 +
13002 +
13003 +
31005 +
51011 +
61009
a|AX_Grenzpunkt +
AX_Aufnahmepunkt +
AX_Sicherungspunkt +
AX_SonstigerVermessungspunkt +
AX_BesondererGebaeudepunkt +
AX_BesondererBauwerkspunkt +
AX_BesondererTopographischerPunkt +
ZUSO +
*REFERENZIERTES*
a|istTeilVon +
*Referenz sinnlos*
a|AX_PunktortTA +
AX_PunktortAG +
AX_PunktortAU +
REO +
*REFERENT*
a|Prüfen, ob Objekt in Spalte 3 weitere ZUSOs referenziert;

* falls nein Objekt in Spalte 3 löschen und gelöschte 
Objektart mit OID im Protokoll ausgeben.

a|13001 +
13003
a|AX_Aufnahmepunkt +
AX_SonstigerVermessungspunkt +
ZUSO

_REFERENT_
a|hat +
*Referenz fehlt*
a|AX_Sicherungspunkt +
ZUSO

_REFERENZIERTES_
|Warnhinweis im Protokoll ausgeben.

|14002 
a|AX_PunktortAG +
REO

REFERENT
a|istTeilVon +
*Referenz fehlt*
a|AX_BesondererGebaeudepunkt +
AX_BesondererBauwerkspunkt

ZUSO

_REFERENZIERTES_
a|Prüfung, ob AX_BesondererGebaeude-/Bauwerkspunkt noch weitere Punktorte
hat.

* Falls nein: Löschung von AX_Punktort_AG ablehnen und Warnhinweis im
Protokoll ausgeben.

Da nicht gewünscht ist, die implizit betroffenen OA punktortweise zu
löschen, wird keine weitere implizite Funktionalität gefordert.

|14003 
a|AX_PunktortAU +
REO

REFERENT
a|istTeilVon +
*Referenz fehlt*
a|(indirekt abgemarkter) +
AX_Grenzpunkt +
AX_Aufnahmepunkt +
AX_Sicherungspunkt +
AX_SonstigerVermessungspunkt +
AX_BesondererTopographischerPunkt +
ZUSO

REFERENZIERTES
a|Prüfung, ob Objekt in Spalte 3 noch weitere Punktorte hat.

* Falls nein: Löschung von AX_Punktort_AU ablehnen und Warnhinweis im
Protokoll ausgeben.

Da nicht gewünscht ist, die implizit betroffenen OA punktortweise zu
löschen, wird keine weitere implizite Funktionalität gefordert.

|14004 
a|AX_PunktortTA +
REO

REFERENT
a|istTeilVon +
*Referenz fehlt*
a|AX_Grenzpunkt +
ZUSO

REFERENZIERTES
a|Prüfung, ob AX_Grenzpunkt noch weitere Punktorte hat.

* Falls nein: Löschung von AX_Punktort_TA ablehnen und Warnhinweis im
Protokoll ausgeben.

Da nicht gewünscht ist, die implizit betroffenen OA punktortweise zu
löschen, wird keine weitere implizite Funktionalität gefordert.

a|21001 +
21006
a|AX_Person +
AX_Namensnummer +
NREO

REFERENZIERTES

REFERENT
a|*...* +
*Referenz sinnlos* +
bzw. +
*Referenz fehlt*
a|AX_ ... +
Mögliche Rollen von 'Person': Eigentümer, Erwerber, Verwalter, Vertreter
in Kataster­angelegenheiten
|Auf implizite Funktionalität wird im Wesentlichen verzichtet, da hier
recht komplexe Verflechtungen bestehen können. Die einfacheren Fälle
werden nachfolgend aufgeführt.

|21001 
a|AX_Person +
NREO +
*REFERENT*
a|bestehtAus +
*Referenz fehlt*
a|AX_Personengruppe +
NREO

REFERENZIERTES
a|Prüfen, ob AX_Personengruppe von anderen Objekten referenziert wird

* Falls nein: AX_Personengruppe löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

Multiplizität der Relation ist [2..*], so dass die Unterschreitung von 2
referenzierten Objekten AX_Person zur impliziten Löschung der
Personengruppe führt.

|21001 
a|AX_Person +
NREO +
*REFERENT*
a|hat +
*Referenz fehlt*
a|AX_Anschrift +
NREO +
*REFERENZIERTES*
a|Prüfen, ob AX_Anschrift von anderen AX_Person oder AX_Dienststelle
referenziert wird

* Wenn nein: AX_Anschrift löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|21001 
a|AX_Person +
NREO +
*REFERENZIERTES*
a|benennt +
*Referenz sinnlos*
a|AX_Namensnummer +
NREO +
*REFERENT*
a|Hier wird meist ein Ersatzobjekt benötigt, daher:

* Warnhinweis im Protokoll ausgeben.

|21001 
a|AX_Person +
NREO

REFERENT
a|wirdVertretenVon +
*Referenz fehlt*
a|AX_Vertretung +
NREO

REFERENZIERTES
a|
* AX_Vertretung (und AX_Person (haengtAn) ) löschen und gelöschte
Objektart mit OID im Protokoll ausgeben

|21001 
a|AX_Person +
NREO

REFERENZIERTES
a|haengtAn +
*Referenz sinnlos*
a|AX_Vertretung +
NREO

REFERENT
a|Prüfen, ob AX_Vertretung anderes Objekt AX_Person mit
"haengtAn" neu referenziert oder von anderen Objekten referenziert wird

* Falls nein: AX_Vertretung löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|21001 
a|AX_Person +
NREO +
*REFERENZIERTES*
a|haengtAn +
*Referenz sinnlos*
a|AX_Verwaltung +
NREO

REFERENT
a|Prüfen, ob AX_Verwaltung anderes Objekt AX_Person mit "haengtAn" neu
referenziert oder von anderen Objekten referenziert wird

* Falls nein: AX_Verwaltung löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.
|21004 
a|AX_Verwaltung +
NREO

REFERENT
a|haengtAn +
*Referenz fehlt*
a|AX_Person +
NREO

REFERENZIERTES
a|Prüfen, ob AX_Person andere Objekte referenziert oder von anderen
Objekten referenziert wird

* Falls nein: AX_Person löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|21005 
a|AX_Vertretung +
NREO

REFERENT
a|haengtAn +
*Referenz fehlt*
a|AX_Person +
NREO

REFERENZIERTES
a|Prüfen, ob AX_Person andere Objekte referenziert oder von anderen
Objekten referenziert wird

* Falls nein: AX_Person löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|21006 
a|AX_Namensnummer +
NREO

*REFERENZIERTES*
a|bestehtAusRechtsverhaeltnissenZu +
*Referenz sinnlos*
a|
AX_Namensnummer +
NREO +
*REFERENT*
a|Prüfen, ob AX_Namensnummer weitere AX_Namensnummer referenziert

* Falls nein: Warnhinweis im Protokoll ausgeben.

|21006 
a|AX_Namensnummer +
NREO +
*REFERENT*
a|hatVorgaenger +
*Referenz fehlt*
a|AX_Namensnummer +
NREO +
*REFERENZIERTES*
|AX_Namensnummer (Vorgänger) löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|21006 
a|AX_Namensnummer +
NREO +
*REFERENT*
a|benennt +
*Referenz fehlt*
a|AX_Person +
NREO +
*REFERENZIERTES*
a|Prüfen, ob AX_Person noch anderweitig referenziert wird

* Falls nein: AX_Person löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|21007 
a|AX_Buchungsblatt +
NREO +
*REFERENZIERTES*
a|istBestandteilVon +
*Referenz sinnlos*
a|AX_Namensnummer +
NREO +
*REFERENT*
|AX_Namensnummer löschen und gelöschte Objektart mit OID im Protokoll
ausgeben..

|21008 
a|AX_Buchungsstelle +
NREO +
*REFERENT*
a|an +
*Referenz sinnlos*
a|AX_Buchungsstelle +
NREO +
REFERENT
a|AX_Buchungsstelle (Referent) löschen und
gelöschte Objektart mit OID im Protokoll ausgeben.

Da die Relation "an" mehrfach vorkommen kann, z.B. bei
Gesamterbbaurecht, ist hier zunächst zu prüfen, ob weitere solche
Referenzen vorhanden sind, bevor die implizite Löschung erfolgen kann.

|21008 
a|AX_Buchungsstelle +
NREO

REFERENT
a|wirdVerwaltetVon +
*Referenz fehlt*
a|AX_Verwaltung +
NREO

REFERENZIERTES
a|Prüfen, ob AX_Verwaltung andere Objekte referenziert oder von anderen
Objekten referenziert wird

* Falls nein: AX_Verwaltung löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|31001 
a|AX_Gebaeude +
REO

_REFERENZIERTES_
a|zeigtAuf +
*Referenz sinnlos*
a|AX_Gebaeudeausgestaltung +
REO

_REFERENT_
|AX_Gebaeudeausgestaltung löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|31001 
a|AX_Gebaeude +
REO

_REFERENT_
a|hat +
*Referenz fehlt*
a|AX_LagebezeichnungMitPseudonummer +
NREO +
*REFERENZIERTES*
a|Prüfen, ob AX_LagebezeichnungMitPseudonummer noch anderweitig
referenziert wird

* Falls nein: AX_LagebezeichnungMitPseudonummer löschen und gelöschte
Objektart mit OID im Protokoll ausgeben.

|31001 
a|AX_Gebaeude +
REO

REFERENT
a|gehoert +
*Referenz fehlt*
a|AX_Person +
NREO

REFERENZIERTES
a|Prüfen, ob AX_Person andere Objekte referenziert oder von anderen
Objekten referenziert wird

* Falls nein: AX_Person löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|73011 
a|AX_Dienststelle +
NREO +
*REFERENT*
a|hat + +
*Referenz fehlt*
a|AX_Anschrift +
NREO +
*REFERENZIERTES*
a|Prüfen, ob AX_Anschrift von anderen AX_Person oder AX_Dienststelle
referenziert wird

* Wenn nein: AX_Anschrift löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|82001 
a|AX_Benutzer +
*REFERENT*
a|gehoertZu +
*Referenz fehlt*
a|AX_Benutzergruppe +
NREO +
*REFERENZIERTES*
a|Prüfen, ob AX_Benutzergruppe von weiteren AX_Benutzer referenziert wird

* Falls nein: AX_Benutzergruppe löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|82001 
a|AX_Benutzer +
NREO +
*REFERENT*
a|ist +
*Referenz fehlt*
a|AX_Person +
NREO +
*REFERENZIERTES*
a|Prüfen, ob AX_Person von anderen Objekten referenziert wird

* Falls nein: AX_Person löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|===


==== Festlegungen für einzelne Relationen des ATKIS- Subschemas

[width="100%",cols="6%,16%,14%,16%,48%",options="noheader",]
|===
2+|*Zu löschendes Objekt* |Betroffene Relation .2+|*"Implizit" betroffene
Objektart* |*Aktion der Datenhaltungskomponente*

2+|Objekt in Sp.1 wird gelöscht, wenn nichts anderes gesagt wird. |*Art des Mangels* |(D.h. was mit den Objekten in Spalte 3 bzw. der
Referenz geschehen soll)
 
|Nr. |Spalte 1 |Spalte 2 |Spalte 3 |Spalte 4

|42002 
a|AX_Strasse +
REO +
REFERENZIERTES
a|bestehtAus +
*Referenz sinnlos*
a|AX_Fahrbahnachse +
REO +
REFERENT
a|Prüfung, ob AX_Strasse von anderen Objekten referenziert wird

* Falls ja: Warnhinweis im Protokoll ausgeben
* Falls nein: AX_Fahrbahnachse löschen und gelöschte Objektart mit OID im
Protokoll ausgeben

|42003 
a|AX_Strassenachse +
REO +
REFERENT
a|istTeilVon +
*Referenz fehlt*
a|AX_Strasse +
REO +
REFERENZIERTES
a|Prüfung, ob AX_Strasse von anderen Objekten referenziert wird

* Falls ja: Warnhinweis im Protokoll ausgeben
* Falls nein: AX_Strasse löschen und gelöschte Objektart mit OID im
Protokoll ausgeben.

|===

[[implfunkt_sekundaernachweis]]
=== Implizite Funktionen im Führungsprozess für ein System zum Sekundärnachweis

[width="100%",cols="6%,16%,14%,16%,48%",options="noheader",]
|===
2+|*Zu löschendes Objekt* |Betroffene Relation .2+|*"Implizit" betroffene
Objektart* |*Aktion der Datenhaltungskomponente*

2+|Objekt in Sp.1 wird gelöscht, wenn nichts anderes gesagt wird. |*Art des Mangels* |(D.h. was mit den Objekten in Spalte 3 bzw. der
Referenz geschehen soll)
 
|Nr. |Spalte 1 |Spalte 2 |Spalte 3 |Spalte 4

a|a)
a|Objekt A +
NREO, REO, ZUSO

_REFERENT_
|... 
a|Objekt B +
NREO, REO, ZUSO

_REFERENZIERTES_
|Wird Objekt A gelöscht, so werden mit ihm auch seine Referenzen,
Überführungs- und Unterführungsrelationen gelöscht.

a|b)
a|Objekt A wird eingetragen +
NREO, REO, ZUSO

_REFERENT_
a|...

*Gegenreferenz fehlt*
a|Objekt B +
NREO, REO, ZUSO

_REFERENZIERTES_
a|
* Die noch fehlende Gegenreferenz von Objekt B auf Objekt A ist bei
Bedarf automatisch zu bilden und einzutragen
* Keine Versionierung von Objekt B.

a|c)
a|Objekt A +
NREO, REO, ZUSO

_REFERENT_
a|...

*Referenz fehlt*
a|Objekt B +
NREO, REO, ZUSO

_REFERENZIERTES_
a|
* Die implementierungstechnische Gegenreferenz von Objekt B auf Objekt A
ist zu löschen
* Keine Versionierung von Objekt B.

|===

Sekundärnachweise können von verschiedenen Systemen mit sehr
unterschiedlichen Fähigkeiten geführt werden. Implizite Fortführungen
des Systems für den Primärnachweis, die über die von einem System für
den Sekundärnachweis verlangten impliziten Funktionen hinausgehen, sind
bei Abgabe der Fortführungsdaten über die NAS in explizite Fortführungen
umzuwandeln. Dieser Forderung wird durch die Versionierung auch der im
Primärnachweis implizit fortgeführten Objekte Rechnung getragen.
