[[metadaten]]
== AdV-Festlegungen zu Metadaten

Metadaten zu Georessourcen enthalten beschreibende Informationen und treffen damit Aussagen über die Eigenschaften von Datensätzen, Datensatzserien, Geodatendiensten und Anwendungen, deren Struktur und inhaltliche Zusammenhänge. Metadaten sind öffentlich zugängliche Daten und ermöglichen, gezielt http://giswiki.org/wiki/Geodaten[Geodaten] zu finden und auf diese zuzugreifen. Sie ermöglichen durch ihren informativen Charakter das Vermeiden redundanter Datenerfassung, das Aufdecken vorhandener Lücken in den Datenbeständen, die Standardisierung von Daten und Begriffen, die Qualitätssicherung für die Datensätze, Vergleiche zwischen alternativen Datenbeständen und das Erzeugen von Transparenz des Datenmarktes.

=== Metadaten für die europäische Geodateninfrastruktur INSPIRE

Die europäische Kommission hat mit der Richtlinie 2007/2/EG den Aufbau einer europäischen Geodateninfrastruktur für die Gemeinschaftspolitik ("INSPIRE") beschlossen. Ein wesentlicher Bestandteil ist dabei das Auffinden von Georessourcen, d.h. Daten und Diensten mittels Metadaten. Die VERORDNUNG (EG) Nr. 1205/2008 DER KOMMISSION vom 3. Dezember 2008 zur Durchführung der Richtlinie 2007/2/EG des Europäischen Parlaments und des Rates hinsichtlich Metadaten legt für den Aufbau einer Europäischen Geodateninfrastruktur verbindlich eine Struktur und einen definierten Mindestumfang an Metadatenelementen fest, die vollständig auch im AdV-Metadatenprofil berücksichtigt wurden. Metadaten sind ferner datensatzbezogen in den Datenspezifikationen von INSPIRE enthalten. Auch diese sind im AdV-Metadatenprofil enthalten.

=== Der Metadatenstandard ISO 19115-1

Der Standard _ISO 19115-1 Geographic Information: Metadata_ bietet ein sehr breites Spektrum zur inhaltlichen Beschreibung von Geodaten. Die Norm enthält mehr als 400 Metadatenelemente, die zur Beschreibung der Geodaten dienen und entweder als verpflichtend (mandatory), bedingt (conditional) oder wahlweise (optional) definiert sind. Um ISO-Konformität zu erreichen, müssen insbesondere alle verpflichtenden Elemente unter Beachtung von konditionalen Zusammenhängen und Kardinalitäten bedient werden. Nutzergruppen können für ihre speziellen Bedürfnisse beliebige Teilmengen (profiles) unter Beachtung der ISO-Konformität definieren. Dabei kann das ISO-Schema auch durch zusätzliche individuelle Elemente (extensions) erweitert werden.

Die ISO 19115-1 in ihrer bisherigen Form berücksichtigt jedoch keine Metadaten zu Diensten. In der ISO 19119 ist ein Kapitel enthalten, das die über die ISO 19115-1 hinausgehenden speziellen Metadaten zur Dokumentation von Diensten auflistet und beschreibt.

=== AdV-Metadatenprofil

Die GeoInfoDok referenziert ein Metadatenprofil von ISO 19115-1, in dem sämtliche für die im AAA-Anwendungsschema verwendeten Elemente aufgeführt sind. Dieses deckt sowohl objektbezogene Metadaten (z.B. Qualitätsinformationen bei Punkten) im AAA-Anwendungsschema als auch datenbestandsbezogene Metadaten ab. Das AdV-Metadatenprofil beinhaltet im Wesentlichen eine Tabelle analog zum ISO 19115-Standard mit deutschen Übersetzungen der Begriffe und Definitionen sowie Erläuterungen für deren Anwendung im Kontext der AdV.

Das AdV-Metadatenprofil ist als eigenständiges Dokument veröffentlicht. Auf der Grundlage von ISO 19115 und 19119 wurden dabei die für die AdV relevanten Elemente extrahiert, übersetzt und erläutert und bilden das AdV-Metadatenprofil. Die Übersetzung der Namen und Beschreibungen aus dem Englischen orientiert sich i.d.R. an der Übersetzung durch eine Arbeitsgruppe der GDI-DE. Ein Umstieg des AdV-Metadatenprofils auf die neue ISO 19115-1 wurde geprüft, aber noch nicht umgesetzt.

Darüber hinaus wurden die durch INSPIRE erfolgten Festlegungen und Vorgaben berücksichtigt, d.h. ein Metadatensatz nach AdV-Metadatenprofil ist zugleich INSPIRE-konform.

Der AdV-Metadatenkatalog war bislang Teil der GeoInfoDok, bis einschließlich der Version 6.0.1. Wegen des übergreifenden Charakters der Metadaten (sie gelten nicht nur für AAA-Daten und AAA-Produkte), wird daraus künftig das AdV-Metadatenprofil als Teil der Serie von AdV-Profilen (wie z.B. das AdV-WMS-Profil), losgelöst von der GeoInfoDok-Versionslogik und eigenständig gepflegt und weiterentwickelt. Sämtliche für das AAA-Anwendungsschema notwendigen Elemente sind im AdV-Metadatenprofil enthalten. Die Metadatenelemente werden in der GeoInfoDok in folgenden Kontexten genutzt:

* Objektbezogene Metadaten, i.d.R. modelliert als integraler Modellbestandteil innerhalb von Attributarten oder als Datentypen innerhalb der Objektarten,
* Produktbezogene Metadaten, die als Bestandteil der Ausgaben mitgeliefert werden können,
* Metadaten der AdV im Metadateninformationssystem (AdV-MIS) zur standardisierten Beschreibung der Daten und Dienste der AdV. Dies ist die Gesamtmenge aller AdV-seitig benötigten Metadaten-Elemente einschließlich der INSPIRE-Metadaten.

Produktbezogene Metadaten sind unterteilt in statische und dynamische Metadaten. Statische Metadaten werden i.d.R. einmal vergeben und ändern sich eher selten (z.B. Kontakt zu einem Dienstleistungszentrum). Dabei wird auf das jeweils gültige AdV-Metadatenprofil verwiesen, d.h. diese sind kein integraler Modellbestandteil sondern Bestandteil des AdV-MIS. Gleichwohl können sie über einen Benutzungsauftrag erfragt und an Nutzer abgegeben werden.

Es gibt drei Möglichkeiten für die Führung der produktbezogenen statischen Metadaten:

* Man führt sie in derselben Datenhaltung wie die Bestandsdaten. Vorteil: Datenhaltung ist autonom, d.h. sie muss bei Produkterstellung nicht auf einen externen Metadaten-Server warten. Handlungsbedarf: Datenhaltung muss zum Metadaten-Server weiterentwickelt werden, sofern eine übergreifende Recherche hierfür erforderlich ist. Zudem muss die Datenhaltung um entsprechende Metadaten-aspekte erweitert werden.
* Man führt sie in einer zu den AAA-Bestandsdaten externen Datenhaltung (z.B. einem Metadaten-Server). Vorteil: die produktbezogenen statischen Metadaten werden übergreifend recherchierbar. Nachteil: Zwei Datenhaltungssysteme werden in Abhängigkeit zueinander gebracht (Wartezeiten bei Metadatenübermittlung).
* Kompromiss: Metadaten in externer Datenhaltung und in derselben Datenhaltung wie die Bestandsdaten im Sinne synchroner Bestände (wobei die AdV nicht festlegt, welcher Bestand Primär- und welcher Sekundärbestand ist).

Welche Variante zum Einsatz kommt, hängt von der jeweiligen Implementierung ab.

Produktbezogene Metadaten setzen sich aus modellseitig statischen (strukturiert nach ISO 19139, einschließlich Abfrage, Transport und Pflege per CSW) und dynamischen zusammen. Umfang und Inhalt der an die Nutzer abgegebenen Metadatenelemente werden produktspezifisch von den Facharbeitskreisen der AdV festgelegt.

Dynamische Metadaten: Werden zur Laufzeit erzeugt, wozu aus nicht persistenten Informationen wie z.B. "Zeitpunkt der Ausführung eines Benutzungsauftrages" Metadaten zum Benutzungsergebnis werden.

Diese Dinge müssen aus fachlicher Sicht definiert und gegebenenfalls in das AAA-Anwendungsschema integriert werden. Die Einrichtung und Fortführung von Metadatenbeständen ist daher noch nicht Bestandteil der Modellierung bzw. der Festlegungen.