[[aufbauinhaltziel]]
== Aufbau, Inhalt und Ziel

=== Ausgangssituation, Motive und Zielvorstellung

Die Vermessungs- und Katasterverwaltungen der Bundesländer haben die Aufgabe, raumbezogene Basisdaten (Geobasisdaten) für Verwaltung, Wirtschaft und private Nutzer zu liefern, und zwar zunehmend in digitaler Form. Hierauf wurde bereits sehr früh reagiert und begonnen, die Daten des Liegenschaftskatasters in den Projekten ALK (Automatisierte Liegenschaftskarte) und ALB (Automatisiertes Liegenschaftsbuch) sowie die Daten der Topographischen Landesaufnahme im Projekt ATKIS (Amtliches Topographisch-Kartographisches Informationssystem) deutschlandweit einheitlich digital zu erfassen und zur Verfügung zu stellen. In den meisten Bundesländern wurde durch Kabinettsbeschluss geregelt, dass die ALK-, ALB- und ATKIS-Daten als Basis für andere Fachinformationssysteme (FIS) zu verwenden sind.

Die Konzepte, nach denen ALB, ALK und ATKIS aufgebaut worden sind, stammen aus den 70er bzw. 80er Jahren des 20. Jahrhunderts. Außerdem wurden daneben weitere umfangreiche digitale Datenbestände nach jeweils eigenen Konzepten der Bundesländer aufgebaut, z. B. Digitale Orthophotos, Rasterdaten der topographischen Landeskartenwerke und Digitale Höhenmodelle.

Vor dem Hintergrund der sich schnell entwickelnden Technik, der inzwischen umfangreichen Erfahrungen der Hersteller bei der Datenerfassung und den sich aus der Datennutzung ergebenden veränderten Anforderungen seitens der Anwender war es erforderlich, diese Konzepte zu überprüfen und weiterzuentwickeln.

Die bisherigen Informationssysteme ALK und ALB werden deshalb zukünftig integriert im Informationssystem *ALKIS* (Amtliches Liegenschaftskatasterinformationssystem) geführt, dabei wird auch die Weiterentwicklung zu 3D-Geobasisdaten aufgegriffen. Insbesondere bei den Gebäuden in ALKIS besteht der Bedarf, optional auch 3D-Informationen abzulegen zu können. Darüber hinaus wurde eine formelle, inhaltliche und semantische Harmonisierung mit ATKIS vorgenommen.

Die *Digitalen Geländemodelle* (DGM) werden in ATKIS nicht wie bisher im Objektbereich Relief einem spezifischen Digitalen Landschaftsmodell (DLM) zugeordnet, sondern als eigenständiger Bestandteil unter den objektstrukturierten Daten ausgewiesen. Hiermit wird, ähnlich wie den Festpunkten der Grundlagenvermessung, die universelle Verwendbarkeit des DGM als eigenständiger Datenbestand verdeutlicht und die Möglichkeit zur Erzeugung von kombinierten Datenbeständen oder Erzeugnissen unter Verwendung von Daten aus anderen Produktgruppen besser herausgestellt.

Für die *Digitalen Orthophotos* (DOP) liegt ein AdV-Standard vor, der zwar nach bisherigem Verständnis keine Anwendung des gemeinsamen Anwendungsschemas ist, der aber trotzdem in die Gesamtdokumentation unter der Überschrift _Bildstrukturierte Daten_ im xref:aaareferenzmodell[xrefstyle=full] aufgenommen wird.

Die Ableitung von *3D-Stadt- und Landschaftsmodellen* aus den Geobasisdaten wird durch die Kombination von 3D-Informationen in ALKIS und den DGM in ATKIS sowie der Geländetexturierung mit DOP ermöglicht.

Zur Nutzung der für den 2D-Bereich definierten Eigenschaften von Geoinformationssystemen wurden die Basisklassen für die Modellierung von 3D-Informationen in das Basisschema integriert. Dadurch könnten die ALKIS - Fortführungsprozesse auch zur wirtschaftlichen Fortführung der 3D - Geobasisdaten genutzt werden.

Zu den Geoinformationen des amtlichen Vermessungswesens gehören auch die Informationen zu den Festpunkten. Da die Festpunkte originär weder zur ALK noch zu ATKIS gehören, wird deren Modellierung nunmehr in einem eigenen Informationssystem *Amtliches Festpunktinformationssystem* (AFIS) durch einen eigenen Objektartenkatalog vorgenommen.

Unter der Überschrift _Dokumentation zur Modellierung der Geoinformationen des amtlichen Vermessungswesens_ werden die AdV-Projekte AFIS, ALKIS und ATKIS mit ihren länderübergreifend festgelegten Eigenschaften in durchgängiger Form gemeinsam beschrieben. Sie werden in einem *gemeinsamen Referenzmodell* miteinander in Beziehung gebracht und im Rahmen dieser Dokumentation in den weiteren Kapiteln als *gemeinsames Anwendungsschema für AFIS, ALKIS und ATKIS* beschrieben.

Das gemeinsame Anwendungsschema sieht die Erfassung und Führung von *Metadaten und Qualitätsdaten* gemäß der ISO-Spezifikationen vor.

=== Grunddatenbestand, Objektartenkataloge und Versionierung

*Grunddatenbestand* ist der von allen Vermessungsverwaltungen der Länder der Bundesrepublik Deutschland in AFIS, ALKIS und ATKIS bundeseinheitlich zu führende und dem Nutzer länderübergreifend zur Verfügung stehende Datenbestand. Dazu gehören auch die entsprechenden Metadaten. Eine spätere Erweiterung des Grunddatenbestandes ist zu erwarten.

Die *Objektartenkataloge* des Liegenschaftskatasters und der Landesvermessung wurden im Interesse einer möglichst einheitlichen Realweltmodellierung soweit möglich und sinnvoll semantisch harmonisiert. Die Harmonisierung hat sowohl Vorteile für die interne Nutzung als auch im externen Bereich. Sie orientiert sich an den bisherigen Katalogen (Muster-OBAK, Verzeichnis der Nutzungsarten, ATKIS-OK).

Im Zusammenhang mit der Beschreibung des Verfahrens zur *Nutzerbezogenen Bestandsdatenaktualisierung* (NBA) wird ein Versionskonzept eingeführt. Länder, die eine Historienverwaltung im Sinne der von der AdV beschlossenen Stufenlösung für ALKIS einsetzen, legen ihrer Modellierung und den darauf basierenden Funktionalitäten einer Historienverwaltung genau dieses um das Versionskonzept erweiterte Anwendungsschema zu Grunde. Hinsichtlich der *Historienverwaltung* wird für ATKIS die stichtagsbezogene Speicherung der jeweiligen Datenbestände für ausreichend erachtet.

Mit der Integration von 3D-Informationen in das gemeinsame Anwendungsschema für AFIS, ALKIS und ATKIS ist auch der Bedarf nach einem Versionierungs- und Historisierungskonzept für 3D-Geobasisdaten abgedeckt.

=== Zielgruppe und Nutzer

Überregionale Nutzer und GIS-Industrie fordern im Hinblick auf die Inhalte und die Strukturierung der Geobasisdaten sowie aus Gründen der Wirtschaftlichkeit die Festlegung eines bundesweit einheitlichen Grunddatenbestandes. Aus der ganzheitlichen Sicht auf das amtliche Vermessungswesen sollen die Grunddatenbestände von AFIS, ALKIS und ATKIS zu diesem Grunddatenbestand der Geodaten des amtlichen Vermessungswesens zusammengeführt werden.

Mit der Europäischen Rahmenrichtlinie zum Aufbau einer Geodateninfrastruktur in Europa *INSPIRE* kommt der standardkonformen Modellierung von Geobasisdaten eine wesentliche Rolle zu. Ein zentrales Ziel von INSPIRE ist die Bereitstellung von mehr und vor allem einheitlichen Geodaten für die Gemeinschaftspolitik und deren Umsetzung in den Mitgliedstaaten auf sämtlichen Ebenen. Der Schwerpunkt liegt dabei auf der Umweltpolitik. In einer europäischen Geodateninfrastruktur können die verschiedenen Geodaten selbst innerhalb einer Fachverwaltung durchaus einen unterschiedlichen Harmonisierungsgrad aufweisen. INSPIRE enthält deshalb drei verschiedene Anhänge, die sich auf unterschiedliche Themenbereiche von Geodaten beziehen, die für einen breiten Bereich umweltpolitischer Maßnahmen erforderlich sind. Je nachdem, ob Geodaten für die Georeferenzierung anderer Daten verwendet werden oder harmonisierte Geodaten für politische Maßnahmen mit direkten oder indirekten Auswirkungen auf die Umwelt erforderlich sind, und je nach Harmonisierungsgrad, der in der Gemeinschaft bereits erreicht ist, gelten unterschiedliche Zielfristen für die Erfüllung der Anforderungen von INSPIRE sowie unterschiedliche Harmonisierungsvorgaben. Wie diese Geodaten organisiert und harmonisiert werden sollen wird nicht hier, sondern in den technischen Ausführungsbestimmungen geregelt.

Durch INSPIRE wird kein umfassendes Programm zur Erfassung neuer Geodaten in den Mitgliedstaaten geschaffen. Stattdessen wird die Dokumentierung vorhandener Geodaten verlangt, um die Nutzung bereits verfügbarer Daten zu optimieren. Dafür werden Dienste (Web Services) festgelegt, die Geodaten besser zugänglich und interoperabel machen, und es wird versucht, Probleme bei der Nutzung von Geodaten zu lösen (Zugriffsrechte, Preise etc.). INSPIRE wird somit den Weg zu einer schrittweisen Harmonisierung von Geodaten in den Mitgliedstaaten ebnen. Mit dem AFIS-ALKIS-ATKIS-Anwendungsschema ist die AdV schon hinreichend für die INSPIRE-konforme Datenabgabe vorbereitet.

Die GIS- und CAD-Anwender haben ferner großes Interesse am Aufbau eines auf den Daten des amtlichen Liegenschaftskatasters aufbauenden 3D - Modells, um ihre Planungen auf dieser amtlichen Grundlage darstellen und besser visualisieren zu können. Des Weiteren finden die anfallenden 3D - Informationen in einem auf der GeoInfoDok basierenden, einheitlichen 3D - Modell eine geeignete Plattform zur Speicherung. Derzeit gibt es für diese Informationen keinen amtlichen Nachweis.

Die *EU-Richtlinie* zur Minderung von Umgebungslärm (2002/49/EG) verpflichtet zukünftig zu regelmäßigen detaillierten Lärmausbreitungsberechnungen, die nur auf der Grundlage von stetig fortgeführten 3D-Stadtmodellen erfolgen können. Auf der GeoInfoDok aufbauende 3D-Informationen bieten die Grundlage zur Ermittlung der Umgebungslärmdaten, bieten Fortführungsmechanismen und ermöglichen die geforderte turnusmäßige Überprüfung der Lärmkartierungen durch die Nutzung des Versionierungs-/Historisierungskonzeptes.

Für die Migration aus den bisherigen Nachweisen ist ein grundsätzliches Vorgehen in Form eines Stufenkonzeptes vorgesehen. Die Detailausarbeitung von Migrationskonzepten ist länderspezifisch auszuführen. Eine Rückmigration in die Schnittstellen der bisherigen Systeme für eine übergangsweise Versorgung der Nutzer mit Daten ist noch für einen längeren Übergangszeitraum denkbar. Das Migrationskonzept besitzt nur temporäre Bedeutung und wird deshalb nicht in die Gesamtdokumentation aufgenommen.